# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/dotnet/sdk:7.0 as build-env
WORKDIR /TodoWebApp
COPY *.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish *.csproj -c Release -o /publish

FROM mcr.microsoft.com/dotnet/aspnet:7.0 as runtime
WORKDIR /publish
COPY --from=build-env /publish .
EXPOSE 7000
ENTRYPOINT [ "dotnet", "TodoWebApp.dll" ]